[package]
name = "youi-tree"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
serde_json.workspace=true
serde = { workspace=true, features = ["derive"] }
serde_repr.workspace=true
petgraph.workspace = true
pad = "0.1.6"

[dev-dependencies]
youi-test={version="1.1.0",path="../test"}
