[package]
name = "youi-calamine"
version.workspace=true
authors = ["Johann Tuffe <tafia973@gmail.com>"]
repository = "https://github.com/tafia/calamine"
documentation = "https://docs.rs/calamine"
description = "An Excel/OpenDocument Spreadsheets reader and deserializer in pure rust"
license = "MIT"
readme = "README.md"
keywords = ["excel", "ods", "xls", "xlsx", "xlsb"]
categories = ["encoding", "parsing", "text-processing"]
exclude = ["tests/**/*"]
edition.workspace=true

[dependencies]
log.workspace = true
serde.workspace = true
byteorder = "1.4"
codepage = "0.1.1"
encoding_rs = "0.8"
once_cell = { version = "1.18", optional = true }

quick-xml = { version = "0.31", features = ["encoding"] }
zip = { version = "0.6", default-features = false, features = ["deflate"] }
chrono = { workspace=true, features = [
    "serde",
], optional = true, default-features = false }

[dev-dependencies]
glob = "0.3"
env_logger = "0.10"
serde_derive = "1.0"
sha256 = "1.3"

[features]
default = []
dates = ["chrono", "once_cell"]
picture = []
