[package]
name = "youi-chart"
version.workspace=true
edition.workspace=true
rust-version.workspace=true

[dependencies]
log.workspace = true
fehler.workspace = true
thiserror.workspace = true
serde_json.workspace = true
serde .workspace = true
itertools.workspace = true
void = "1.0.2"
polars-core={workspace = true,features=["ndarray"]}
polars-io = {workspace = true,features=["json","csv"]}
ndarray.workspace = true

linfa = "0.7.0"
linfa-linear = "0.7.0"
linfa-datasets = {version= "0.7.0",features=["diabetes"]}

youi-report={version="1.1.0",path="../report"}

[dev-dependencies]
youi-test={version="1.1.0",path="../test"}
