[package]
name = "youi-chart"
version.workspace=true
edition.workspace=true
rust-version.workspace=true

[dependencies]
log.workspace = true
fehler.workspace = true
thiserror.workspace = true
serde_json.workspace = true
serde .workspace = true
itertools.workspace = true

polars-core.workspace = true
polars-io = {workspace = true,features=["json"]}

[dev-dependencies]
youi-test={version="1.1.0",path="../test"}