[workspace]
members = [
    "stats-geo/geo",
    "stats-geo/sqlite",
    "stats-geo/geo-impl",
]

resolver = "2"

[workspace.package]
version = "1.1.0"
edition = "2021"
description = "app services"
repository = ""
keywords = ["services"]
categories = ["youi"]
license = "MIT OR Apache-2.0"
rust-version = "1.65.0"

[workspace.dependencies]
async-trait = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
sqlx = "0.7"
thiserror = "1.0"
tokio = "1.19"
cached = "0.51"

youi-geo = {version="1.1.0",path="../youi/geo"}
youi-test = {version="1.1.0",path="../youi/test"}