[package]
name = "youi-report"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
serde_json.workspace=true
serde = { workspace=true, features = ["derive"] }
serde_repr.workspace=true
youi-table = {version = "1.1.0",path="../table"}
youi-flow = {version = "1.1.0",path="../flow"}
grid = {workspace=true,features=["serde"]}
itertools.workspace = true
petgraph.workspace = true
ndarray.workspace = true
uuid = {workspace=true,features = ["serde", "v4"]}
rayon.workspace = true
pad = "0.1.6"
regex.workspace = true
rhai.workspace = true

[dev-dependencies]
youi-test={version="1.1.0",path="../test"}
