[package]
name = "youi-query"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
serde_json.workspace=true
serde = { workspace=true, features = ["derive"] }
serde_repr.workspace=true
itertools.workspace = true
youi-tree={version="1.1.0",path="../tree"}
youi-table={version="1.1.0",path="../table"}

[dev-dependencies]
youi-test={version="1.1.0",path="../test"}
