[package]
name = "youi-geo"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
serde_json.workspace=true
serde = { workspace=true, features = ["derive"] }
serde_repr.workspace=true
rayon.workspace = true
polars-core ={workspace = true,features=["rows"]}
polars-io ={workspace = true,features=["csv"]}
geo = "0.28.0"
geojson = "0.24.1"

[dev-dependencies]
youi-test={version="1.1.0",path="../test"}
