[workspace]
members = [
    "calamine",
    "flow",
    "etl",
    "sql",
    "search",
    "dataframe",
    "table",
    "report",
    "dsl",
    "code",
    "test"
]

resolver = "2"

[workspace.package]
version = "1.1.0"
edition = "2021"
description = "youi query framework."
repository = ""
keywords = ["youi-data-query"]
categories = ["youi"]
license = "MIT OR Apache-2.0"
rust-version = "1.65.0"

[workspace.dependencies]
actix-web = "4.5.1"
anyhow = "1.0"
async-trait = "0.1.77"
arrow2="0.17"
chrono = "0.4"
fehler = "1"
fern="0.6"
grid = "0.13.0"
itertools = "0.11"
jieba-rs = "0.6"
lazy_static = "1.4.0"
log = "0.4"
ndarray = "0.15.3"
num-traits = "0.2.14"
petgraph = "0.6.3"
polars-arrow = "0.39"
polars-core = "0.39"
polars-io = "0.39"
polars-lazy = "0.39"
polars-ops = "0.39"
polars-time = "0.39"
polars-utils = "0.39"
rayon = "1.7.0"
regex = "1.10.3"
rhai = "1.18.0"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1.8"
sqlx = "0.7.1"
thiserror = "1.0"
tokio = "1.19"
uuid = "1.7.0"