[package]
name = "youi-sql"
version.workspace = true
edition.workspace = true
#rust-version.workspace = true

[dependencies]
fehler.workspace = true
thiserror.workspace = true
serde_json .workspace = true
serde.workspace = true
anyhow.workspace = true
chrono.workspace = true
log.workspace = true
itertools.workspace = true
polars-core.workspace = true
polars-arrow={workspace = true,features=["arrow_rs"]}
arrow-schema = "51.0.0"

serde_repr = "0.1"
sqlparser = "0.36"
owning_ref = "0.4"
rusqlite = {version="0.29", features = ["column_decltype", "chrono", "bundled"], optional = true}
r2d2 = {version="0.8.10", optional = true}
fallible-streaming-iterator = {version = "0.1", optional = true}

futures = {version="0.3.21",features=["thread-pool"]}
rayon.workspace = true
url = "2"
urlencoding = {version = "2.1", optional = true}

openssl = {version = "0.10", optional = true}
postgres = {version = "0.19", features = ["with-chrono-0_4", "with-uuid-1", "with-serde_json-1"], optional = true}
r2d2_postgres = {version = "0.18.1", optional = true}
postgres-native-tls = {version = "0.5", optional = true}
postgres-openssl = {version = "0.5", optional = true}

rust_decimal = {version = "1", features = ["db-postgres"], optional = true}
rust_decimal_macros = {version = "1", optional = true}
uuid = {workspace=true, optional = true}
csv = {version = "1", optional = true}
hex = {version = "0.4", optional = true}
num-traits = {workspace=true, optional = true}

[features]
default = ["fptr","src_postgres"]
src_sqlite = ["rusqlite","r2d2","urlencoding","fallible-streaming-iterator"]
#src_kingbase = ["r2d2","kingbase","r2d2_kingbase"]
src_postgres=[
    "r2d2",
    "postgres",
    "r2d2_postgres",
    "postgres-native-tls",
    "postgres-openssl",
    "openssl",
    "rust_decimal",
    "rust_decimal_macros",
    "uuid",
    "csv",
    "hex",
    "num-traits"
]
fptr=[]
