[package]
name = "youi-ml"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
serde_json.workspace=true
serde = { workspace=true, features = ["derive"] }
serde_repr.workspace=true
rayon.workspace = true
polars-core={workspace = true,features=["ndarray"]}
polars-io = {workspace = true,features=["json","csv"]}
ndarray.workspace = true

linfa = "0.7.0"
linfa-linear = "0.7.0"
linfa-datasets = {version= "0.7.0",features=["diabetes"]}

youi-report={version="1.1.0",path="../report"}
youi-flow={version="1.1.0",path="../flow"}

[dev-dependencies]
youi-test={version="1.1.0",path="../test"}
